menu:
- {name: 'About', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Research', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/jrastinejad'}
- {icon: 'twitter', link: 'https://twitter.com/jillian_rast'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jillian-rastinejad-37b532156'}

contacts:
- {name: 'Jillian Rastinejad', title: 'NASA Einstein Fellow', department: 'Department of Astronomy', institution: 'University of Maryland', phone: '(000) 000-0000', email: 'jcrastin [at] umd.edu', office: '4296 Stadium Dr., Physical Sciences Complex, College Park, MD 20742', image: 'assets/img/headshot.jpg'}
