menu:
- {name: 'About', url: '/about'}
- {name: 'Publications', url: '/publications'}
- {name: 'Research', url: '/research'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Jillian Rastinejad', title: 'PhD Candidate and Northwestern Presidential Fellow', department: 'CIERA & Dept. of Physics & Astronomy', institution: 'Northwestern University', phone: '(000) 000-0000', email: 'jillianrastinejad2024 [at] u.northwestern.edu', office: '1800 Sherman Ave., Evanston, IL, USA', image: 'assets/img/headshot.jpg'}
